# Generated by Django 5.2.5 on 2025-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_drone',
            field=models.BooleanField(default=False),
        ),
    ]
