# Generated by Django 5.2.5 on 2025-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0002_video_is_analysis_video_is_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_footballer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('sweeper', 'Sweeper'), ('centerback', 'Centerback'), ('fullback', 'Fullback'), ('wingback', 'Wingback'), ('defensive midfielder', 'Defensive midfielder'), ('central midfielder', 'Central midfielder'), ('attacking midfielder', 'Attacking midfielder'), ('winger', 'Winger'), ('striker', 'Striker'), ('observer', 'Observer')], default='observer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('blank', 'Blank')], default='blank', max_length=6),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('game', 'Game'), ('training', 'Training')], default='training', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='recorded_on',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
