# Generated by Django 5.2.5 on 2025-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0003_userprofile_active_footballer_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='mux_playback_policy',
            field=models.CharField(choices=[('public', 'Public'), ('signed', 'Signed')], default='public', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Current place of residence.', max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='+123456789, 0123456789, 123456789', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('sweeper', 'Sweeper'), ('center-back', 'Center-back'), ('full-back', 'Full-back'), ('wing-back', 'Wing-back'), ('defensive midfielder', 'Defensive midfielder'), ('central midfielder', 'Central midfielder'), ('attacking midfielder', 'Attacking midfielder'), ('winger', 'Winger'), ('striker', 'Striker'), ('observer', 'Observer')], default='observer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, help_text='Professional footballer, Engineer, Business owner...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, help_text='Place of video recording.', max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='recorded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
