# Generated by Django 5.2.5 on 2025-09-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_2_10'),
        ('video_management', '0004_video_mux_playback_policy_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(blank=True, help_text="The team's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer')),
                ('subscription', models.ForeignKey(blank=True, help_text="The team's Stripe subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, help_text='The team whose enterprise subscription a user has access to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_management.team'),
        ),
    ]
