# Generated by Django 5.2.5 on 2025-09-11 07:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0005_userprofile_customer_userprofile_subscription_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 7, 34, 10, 737627, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, help_text='The team whose enterprise subscription a user has access to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='video_management.team'),
        ),
    ]
