# Generated by Django 5.2.5 on 2025-09-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0008_playbackhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbackhistory',
            options={'verbose_name': 'Video watch progress', 'verbose_name_plural': 'Videos watch progress'},
        ),
    ]
