# Generated by Django 5.2.5 on 2026-02-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0011_replace_mux_with_bunny_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_library_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
