# Generated by Django 5.2.5 on 2026-03-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0013_userprofile_access_expires_at_paymenttransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='video_manag_provide_66a318_idx',
            old_name='video_manage_provider_5a7f7d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='video_manag_provide_0d0a8e_idx',
            old_name='video_manage_provider_9adc01_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='video_manag_externa_660648_idx',
            old_name='video_manage_externa_5d5df2_idx',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('STRIPE', 'Stripe')], max_length=20),
        ),
    ]
