# Generated by Django 5.1.6 on 2026-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0016_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
    ]
