# Generated by Django 5.1.6 on 2026-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0018_alter_video_owner_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('sweeper', 'Sweeper'), ('center-back', 'Center-back'), ('full-back', 'Full-back'), ('wing-back', 'Wing-back'), ('defensive midfielder', 'Defensive midfielder'), ('central midfielder', 'Central midfielder'), ('attacking midfielder', 'Attacking midfielder'), ('winger', 'Winger'), ('striker', 'Striker'), ('coach', 'Coach'), ('observer', 'Observer')], default='observer', max_length=20),
        ),
    ]
