# Generated by Django 5.1.6 on 2026-06-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0019_alter_userprofile_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaybackHistory',
        ),
    ]
