# Generated by Django 5.1.6 on 2026-07-07 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0020_delete_playbackhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='video_manag_user_id_4eee28_idx'),
        ),
    ]
