# Generated by Django 5.1.6 on 2026-07-07 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_options'),
        ('video_management', '0021_paymenttransaction_video_manag_user_id_4eee28_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', '-created_at'], name='playlists_p_owner_i_92a72a_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_public', '-created_at'], name='playlists_p_is_publ_68137c_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_playlist_name_per_owner'),
        ),
    ]
