#!/usr/bin/env node
/**
 * 'contentService.js' handles provision of playlist and video objects
 *		       with pagination and lazy loading.
 */

import apiClient from './apiClient';

/**
 * @class
 *
 * 'ContentService' encapsulates the attributes and methods required for
 * 		    effective backend delivery of video content as well as
 *		    frontend caching and distribution.
 */
class ContentService {
    // Creates an instance of the ContentService class
    constructor() {
	// Maps' keys can be of complex data type, not just string (JS Objects)
	this.cache = new Map();

	this.prefetchQueue = [];
	this.isPrefetching = false;
    }

    /**
     * Asynchronous function.
     * Fetches paginated playlists.
     *
     * @param {Number} page - The nth pagination section requested.
     * @param {Number} limit - The number of elements found on the page.
     *
     * @returns {Object} A set of paginated playlists with the metadata.
     */
    async fetchPlaylists(page = 1, limit = 3) {
	const cacheKey = `playlists_${page}_${limit}`;

	// Check cache first
	if (this.cache.has(cacheKey)) {
	    return this.cache.get(cacheKey);
	}

	try {
	    const response = await apiClient.get('/playlists/', {
		params: { page, limit },
	    });

	    const data = {
		playlists: response.data.results ?? [],
		hasMore: Boolean(response.data.next),
		nextPage: page + 1,
		totalCount: response.data.count ?? 0,
	    };

	    // Cache the results
	    this.cache.set(cacheKey, data);

	    // Prefect the next page in the background
	    if (data.hasMore) {
		this.prefetchPage(page + 1, limit);
	    }

	    return data

	} catch (error) {
	    console.error('Failed to fetch playlists: ', error);

	    return {
		playlists: [],
		hasMore: false,
		nextPage: page,
		totalCount: 0,
	    };
	}
    }

    /**
     * Asynchronous function.
     * Fetches videos for a specific playlist with pagination
     *
     * @param {string} playlistId - UUID tied to the playlist object.
     * @param {Number} page - The page on which the playlist if found.
     * @param {Number} limit - The maximum number of videos to be fetched.
     *
     * @returns {Object} The set of videos tied to a playlist, paginated
     *			 and with the metadata.
     */
    async fetchPlaylistVideos(playlistId, page = 1, limit = 10) {
	const cacheKey = `playlist_${playlistId}_${page}_${limit}`;

	if (this.cache.has(cacheKey)) {
	    return this.cache.get(cacheKey);
	}

	try {
	    const response = await apiClient.get(`/playlists/${playlistId/videos/}`, {
		params: { page, limit },
	    });

	    const data = {
		videos: response.data.results ?? [],
		hasMore: Boolean(response.data.next),
		nextPage: page + 1,
	    };

	    this.cache.set(cacheKey, data);

	    return data;

	} catch (error) {
	    console.error(`Failed to fetch videos for playlist ${playlistId}: `, error);
	    return { videos: [], hasMore: false, nextPage: page };
	}
    }

    /**
     * Asynchronous function.
     * Prefetches the next page in the background.
     *
     * @param {Number} page - The page segment required.
     * @param {Number} limit - The maximum number of items to be fetched.
     */
    async prefetchPage(page, limit) {
	if (this.isPrefetching) {
	    this.prefetchQueue.push({ page, limit });
	    return;
	}

	this.isPrefetching = true;

	try {
	    // Silently fetch and cache the playlists
	    await this.fetchPlaylists(page, limit);

	    // Process queue if any
	    if (this.prefetchQueue.length > 0) {
		const next = this.prefetchQueue.shift();

		await this.prefetchPage(next.page, next.limit);
	    }

	} finally {
	    this.isPrefetching = false;
	}
    }

    /**
     * Asynchronous function.
     * Handles content delivery upon use of the search functionality.
     *
     * @param {string} query - The search bar input generated by the user.
     * @param {Object} filters - The traits guiding selection of the content.
     *
     * @returns {Object} A set of videos and/or playlists matching the search.
     */
    async searchContent(query, filters = {}) {

	try {
	    const response = await apiClient.get('/search', {
		params: {
		    q: query,
		    ...filters
		}
	    });

	    return {
		videos: response.data.videos || [],
		playlists: response.data.playlists || [],
	    };

	} catch (error) {
	    console.error('Search failed: ', error);

	    return { videos: [], playlists: [] };
	}
    }

    /**
     * Asynchronous function.
     * Gets a video's details with Mux playback info excluded.
     *
     * @param {string} videoId - UUID of the video whose details are needed.
     *
     * @returns {Object} The video object requested.
     */
    async getVideoDetails(videoId) {
	const cacheKey = `video_${videoId}`;

	if (this.cache.has(cacheKey)) {
	    return this.cache.get(cacheKey);
	}

	try {
	    const response = await apiClient.get(`/videos/${videoId}/`);
	    const video = response.data;

	    this.cache.set(cacheKey, video);

	    return video;

	} catch (error) {
	    console.error(`Failed to fetch video ${videoId}: `, error);

	    return null;
	}
    }

    /**
     * Prefetches video thumbnails.
     *
     * @param {Array} videos - The set of videos whose thumbnails are needed.
     */
    prefetchThumbnails(videos) {
	if (!videos || videos.length === 0) return;

	videos.forEach((video) => {
	    if (video.thumbnail_url) {
		const img = new Image();
		img.src = video.thumbnail_url;
	    }
	});
    }

    // Clear cache (useful for memory management)
    clearCache() {
	this.cache.clear();
    }

    /**
     * Asynchronous function.
     * Get a video set recommendation, potentially based on a particular video.
     *
     * @param {string} videoId - Optional video off of which the recommendation
     *     			 is extracted.
     *
     * @returns {Array} A set of recommended videos.
     */
    async getRecommendations(videoId = null) {

	try {
	    const endpoint = videoId
		  ? `/videos/${videoId}/recommendations/`
		  : '/recommendations/';

	    const response = await apiClient.get(endpoint);

	    return response.data;
	} catch (error) {
	    console.error('Failed to fetch recommendations: ', error);

	    return [];
	}
    }

}

export default new ContentService();
