# Generated by Django 5.2.5 on 2026-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#0D1C23', max_length=7),
        ),
    ]
